<td>
	<div class="text-right pull-right" style="width: 90px;">
		<?php if ($editable): ?>
			<a href="<?= $editUrl ?>" class="btn btn-default btn-sm"><i class="fa fa-pencil"></i></a>
		<?php endif ?>
        <?php if ($deletable): ?>
			<form action="<?= $deleteUrl ?>" method="POST" style="display:inline-block;">
				<button class="btn btn-danger btn-sm btn-delete">
					<i class="fa fa-times"></i>
				</button>
			</form>
        <?php endif ?>
        <?php if ($restorable): ?>
			<form action="<?= $restoreUrl ?>" method="POST" style="display:inline-block;">
				<button class="btn btn-primary btn-sm">
					<i class="fa fa-reply"></i>
				</button>
			</form>
        <?php endif ?>
	</div>
</td>