<?php if ( ! empty($title)): ?>
    <div class="row">
        <div class="col-lg-12">
            <h2 style="margin-top:0;"><small><?= $title ?></small></h2>
        </div>
    </div>
<?php endif; ?>
<?php if ($creatable) : ?>
    <a class="btn btn-primary" href="<?= $createUrl ?>"><i class="fa fa-plus"></i>New</a>
<?php endif ?>
<div class="pull-right tableActions">
    <?php foreach ($actions as $action): ?>
        <?= $action->render() ?>
	<?php endforeach ?>
</div>
<table class="table table-striped datatables" data-url="<?= $url ?>">
    <thead>
    <tr>
        <?php foreach ($columns as $column): ?>
            <?= $column->header()->render(); ?>
        <?php endforeach; ?>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <?php foreach ($columns as $index => $column): ?>
            <?php $columnFilter = !empty($columnFilters[$index]) ? $columnFilters[$index] : null; ?>
            <td data-index="<?= $index ?>"><?= $columnFilter ?></td>
        <?php endforeach ?>
    </tr>
    </tfoot>
    <tbody>
    </tbody>
</table>