<?php
/**
 * @var $this \Phalcon\Mvc\View
 *
 */
?>
<ul class="nav nav-stacked">
    <!-- Main menu -->
    <li>
        <a href="<?= $this->url->get(['for' => 'backend-user-main']) ?>">
            Пользователи
        </a>
    </li>
    <li>
        <a href="<?= $this->url->get(['for' => 'backend-seorules-main']) ?>">
            SEO правила
        </a>
    </li>
    <li>
        <a href="<?= $this->url->get(['for' => 'backend-seotitles-main']) ?>">
            SEO для ссылок
        </a>
    </li>
</ul>
