<div class="form-group

    <?php
        $messages = $validation->getMessages();
        echo $messages ? ($validation->getMessages()->filter($name) ? 'has-error' : '') : '';
    ?>">

    <label for="<?= $name ?>"><?= $label ?></label>
    <input class="form-control" name="<?= $name ?>" type="text" id="<?= $name ?>" value="<?= $value ?>">
    <?php
        if ($messages) {
            $this->partial('Formitem/errors');
        }
    ?>
</div>