<?= $this->getContent(); // главное содержимое ?>
<?php

/**
 * @var $form \Mytutcodim\Forms\Decorator\BootstrapDecorator
 */

?>
<div class="content-box">
    <div class="panel-heading">
        <div class="panel-title">SEO правила</div>
    </div>
    <div class="panel-body">
        <?= $form->renderForm(); ?>
    </div>
    <?php if ( ! empty($key)) : ?>
    <div class="panel-body">
        <a class="btn btn-danger" href="<?= $this->url->get(['for' => 'backend-seotitles-delete', 'id' => $key]) ?>">Удалить</a>
    </div>
    <?php endif ?>
</div>
