<?php
/**
 * @var $pager Mytutcodim\Paginator\Pager
 * @var $this  Phalcon\Mvc\View
 */
?>
<?php if (count($pager) == 0): ?>
    <p>Жаль, но тут ничего нет, <a href="<?= $this->url->get(['for' => 'backend-seotitles-create']) ?>">создать!</a>
<?php else: ?>
    <div class="content-box">
        <div class="panel-heading">
            <div class="panel-title">SEO правила</div>
            <div class="panel-options">
                <div class="btn-group">
                    <a href="<?= $this->url->get(['for' => 'backend-seotitles-create']) ?>" class="btn btn-success"><i
                            class="glyphicon glyphicon-plus-sign"></i> Создать</a>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-responsive table-hover">
                    <thead>
                    <tr>
                        <th data-width="10">#id</th>
                        <th>Заголовок</th>
                        <th>Ссылка</th>
                        <th>H1</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($pager as $item): ?>
                        <?php $href = $this->tag->linkTo(
                            [['for' => 'backend-seotitles-edit', 'id' => $item->id], ($item->title==''?'Редактировать':$item->title)]
                        ) ?>
                        <tr>
                            <td><?php echo $item->id ?></td>
                            <td><?php echo $href ?></td>
                            <td><?php echo $item->url ?></td>
                            <td><?php echo $item->h1 ?></td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="4">
                            <?= !$pager->haveToPaginate() ? '' : $pager->getLayout() ?>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
<?php endif ?>
