<div class="login-wrapper">
    <div class="box">
        <div class="content-wrap">
            <h6>Log In</h6>
            <form method="post">

                <?= $form->render('name') ?>
                <?= $form->render('password') ?>
                <?= $form->render('go') ?>
                <!--<input class="form-control" type="text" placeholder="E-mail address">
                <input class="form-control" type="password" placeholder="Password">
                <div class="action">
                    <a class="btn btn-primary signup" href="index.html">Login</a>
                </div>-->
            </form>
        </div>
    </div>
</div>