<div class="col-md-4 col-md-offset-4">
    <div class="login-wrapper">
        <div class="box">
            <div class="content-wrap">
                <h6>Log In</h6>
                <form method="post">

                    <?= $form->render('name') ?>
                    <?= $form->render('password') ?>
                    <div class="action">
                        <?= $form->render('log in') ?>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>